# Generated by Django 4.1.7 on 2023-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=500)),
                ('expertise', models.CharField(max_length=255)),
                ('experience', models.TextField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
