# Generated by Django 4.1.7 on 2023-12-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='age',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='certificate',
            field=models.FileField(default=' ', max_length=500, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='image',
            field=models.ImageField(default='', max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='bio',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='experience',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
