# Generated by Django 4.1.7 on 2023-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0003_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='syllabus',
            field=models.TextField(default='Default Syllabus', max_length=500),
        ),
    ]
