# Generated by Django 4.1.7 on 2023-12-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0004_class_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
