# Generated by Django 4.1.7 on 2023-12-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0005_alter_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
