# Generated by Django 5.0.1 on 2024-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0008_mentorprofile_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
