# Generated by Django 5.0.1 on 2024-02-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0009_alter_mentorprofile_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='certificate',
            field=models.FileField(blank=True, default='', max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=500, null=True, upload_to=''),
        ),
    ]
