# Generated by Django 5.0.1 on 2024-02-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
