# Generated by Django 5.0.1 on 2024-02-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0012_remove_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorapp.mentorprofile'),
        ),
    ]
