# Generated by Django 5.0.1 on 2024-02-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0013_alter_order_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
