# Generated by Django 5.0.1 on 2024-03-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorapp', '0016_order_confirmation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='thumbnail',
            field=models.CharField(default='', max_length=500),
        ),
    ]
