# Generated by Django 5.0.1 on 2024-03-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('mentorapp', '0017_alter_class_thumbnail'),
        ('myapp', '0007_userprofile_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_mentor', to='mentorapp.mentorprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_user', to='myapp.userprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_mentor', to='mentorapp.mentorprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_user', to='myapp.userprofile'),
        ),
    ]
