# Generated by Django 5.0.1 on 2024-03-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmessage_receiver_mentor_and_more'),
        ('mentorapp', '0017_alter_class_thumbnail'),
        ('myapp', '0007_userprofile_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentortoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('mentor', 'Mentor')], default='mentor', max_length=10)),
                ('receiver_type', models.CharField(choices=[('user', 'User'), ('mentor', 'Mentor')], default='user', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='myapp.userprofile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='mentorapp.mentorprofile')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
