# Generated by Django 5.0.1 on 2024-03-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentorapp', '0017_alter_class_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorapp.order')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
