# Generated by Django 5.0.1 on 2024-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallsession',
            name='channel_name',
            field=models.CharField(default='video_call_{uuid.uuid4().hex}', max_length=255),
        ),
    ]
