# Generated by Django 5.0.1 on 2024-03-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocall', '0002_videocallsession_channel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocallsession',
            options={},
        ),
    ]
