# Generated by Django 4.1.7 on 2023-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.PositiveBigIntegerField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
